#!/bin/bash
# mycat requires bashisms, so we can't be portable-sh here.
source "${BASH_SOURCE[0]%/*}/mycat.sh"
loadavg() {
	mycat /proc/loadavg
}
if [ "${BASH_SOURCE}" = "$0" ]; then
	loadavg "$@"
fi
